package eu.europeana.annotation.definitions.model.vocabulary;

public enum SelectorTypes {
	DATA_POSITION_SELECTOR, FRAGMENT_SELECTOR, SVG_SELECTOR, TEXT_POSITION_SELECTOR, TEXT_QUOTE_SELECTOR, RDF_STATEMENT_SELECTOR, SVG_RECTANGLE_SELECTOR
}
