resources:
  - ../../base
  - service.yaml
  - ingress.yaml
  - hpa.yaml

labels:
  - includeSelectors: true
    pairs:
      app: annotation-api

patches:
  - path: deployment_patch.yaml
  
# expects files to be in the same directory
secretGenerator:
  - name: ibm-secret
    files:
      - ibm-databases-truststore.jks