<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>annotation-api</artifactId>
		<groupId>eu.europeana.annotation</groupId>
		<relativePath>../pom.xml</relativePath>
		<version>0.5.1-SNAPSHOT</version>
	</parent>
	<artifactId>annotation-tests</artifactId>
	<name>Annotation Tests</name>
	<description>Annotation tests.</description>

	<properties>
		<sonar.coverage.jacoco.xmlReportPaths>
			${project.basedir}/../${aggregate.report.xml}</sonar.coverage.jacoco.xmlReportPaths>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>eu.europeana.annotation</groupId>
			<artifactId>annotation-web</artifactId>
			<version>0.5.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>eu.europeana.annotation</groupId>
			<artifactId>annotation-definitions</artifactId>
			<version>0.5.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-test-autoconfigure</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>mongodb</artifactId>
			<version>${version.testcontainers}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${version.testcontainers}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>mockwebserver</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.jetbrains/annotations -->
		<dependency>
			<groupId>org.jetbrains</groupId>
			<artifactId>annotations</artifactId>
			<version>23.0.0</version>
		</dependency>

	</dependencies>
	<profiles>
		<profile>
			<id>coverage</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<version>${jacoco-plugin.version}</version>
						<executions>
							<execution>
								<phase>verify</phase>
								<goals>
									<goal>report-aggregate</goal>
								</goals>
								<!-- include the reports from all modules -->
								<configuration>
									<dataFileIncludes>
										<dataFileInclude>**/jacoco.exec</dataFileInclude>
									</dataFileIncludes>
									<outputDirectory>
										${project.reporting.outputDirectory}/jacoco-aggregate
									</outputDirectory>
								</configuration>
							</execution>
						</executions>
					</plugin>

					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-failsafe-plugin</artifactId>
						<version>${version.maven-failsafe-plugin}</version>
						<executions>
							<execution>
								<goals>
									<goal>integration-test</goal>
									<goal>verify</goal>
								</goals>
							</execution>
						</executions>

						<!-- useModulePath = false Fixes Integration test not
						finding beans. May
							be
					removed with 3.0.0-M6 is available
                    See: https://stackoverflow.com/a/65806777/14530159 -->
						<configuration>
							<useModulePath>false</useModulePath>
						</configuration>

					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
