spring.main.allow-bean-definition-overriding=true
springfox.documentation.swagger-ui.enabled=true
server.port = 8080

## management / actuator / swagger
management.security.enabled=false

management.endpoints.web.exposure.include=health,info
# for debugging conditioonal annotations locally the following configuration can be used
management.info.build.enabled=true
management.info.git.enabled=true
management.health.probes.enabled=true

## Configurations for swagger console
springdoc.paths-to-exclude=/error
springdoc.show-actuator=true
