resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: annotation-api

# expects files to be in the same directory
secretGenerator:
  - name: annotation-api-properties
    files:
      - annotation.user.properties