resources:
  - deployment.yaml

commonLabels:
  app: annotation-api

# expects files to be in the same directory
secretGenerator:
  - name: annotation-api-properties
    files:
      - annotation.user.properties